Use single event structure to configure both boot.iso and repository

diff --git a/.github/workflows/scenarios-permian.yml b/.github/workflows/scenarios-permian.yml
--- a/.github/workflows/scenarios-permian.yml
+++ b/.github/workflows/scenarios-permian.yml
@@ -62,15 +62,29 @@ jobs:
           BOOT_ISO_URL="file://$BOOT_ISO_PATH"
           if [ "${{ matrix.scenario }}" == "daily-iso" ] || [ "${{ matrix.scenario }}" == "minimal" ]; then
             ${{ github.workspace }}/kickstart-tests/containers/runner/fetch_daily_iso.sh $GITHUB_TOKEN $BOOT_ISO_PATH
-          elif [ "${{ matrix.scenario }}" == "rhel8" ]; then
-            curl -L http://download.eng.bos.redhat.com/rhel-8/development/RHEL-8/latest-RHEL-8.6/compose/BaseOS/x86_64/os/images/boot.iso --output $BOOT_ISO_PATH
-          elif [ "${{ matrix.scenario }}" == "rhel9" ]; then
-            curl -L http://download.eng.bos.redhat.com/rhel-9/development/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/images/boot.iso --output $BOOT_ISO_PATH
           else
             echo "Boot.iso for ${{ matrix.scenario }} not configured"
             BOOT_ISO_URL=
           fi
           echo "::set-output name=boot_iso::$BOOT_ISO_URL"
+
+      # Configure location of installation repositories for the scenario
+      # Also default boot.iso comes from the installationUrls event value
+      - name: Set installation_tree for the scenario
+        id: set_installation_urls
+        run: |
+          set -eux
+          if [ "${{ matrix.scenario }}" == "rhel8" ]; then
+            echo "::set-output name=installation_tree::http://download.eng.bos.redhat.com/rhel-8/development/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os"
+            echo "::set-output name=modular_url::http://download.eng.bos.redhat.com/rhel-8/development/RHEL-8/latest-RHEL-8/compose/AppStream/x86_64/os"
+          elif [ "${{ matrix.scenario }}" == "rhel9" ]; then
+            echo "::set-output name=installation_tree::http://download.eng.bos.redhat.com/rhel-9/development/RHEL-9/latest-RHEL-9/compose/BaseOS/x86_64/os"
+            echo "::set-output name=modular_url::http://download.eng.bos.redhat.com/rhel-9/development/RHEL-9/latest-RHEL-9/compose/AppStream/x86_64/os"
+          else
+            echo "::set-output name=installation_tree::"
+            echo "::set-output name=modular_url::"
+            echo "Installation tree location for ${{ matrix.scenario }} not configured"
+          fi
 
       - name: Set launcher timeout from job timeout
         id: set_timeout
@@ -80,7 +94,7 @@ jobs:
 
       - name: Run scenario ${{ matrix.scenario }} in container
         working-directory: ./permian
-        run: sudo --preserve-env=TEST_JOBS PYTHONPATH=${PYTHONPATH:-}:${{ github.workspace }}/tclib ./pipeline --debug-log permian.log -o library.directPath="${{ github.workspace }}/kickstart-tests/testlib" -o kickstart_test.retry_on_failure=True -o workflows.dry_run=False -o kickstart_test.kstest_local_repo="${{ github.workspace }}/kickstart-tests" -o kickstart_test.timeout="${{ steps.set_timeout.outputs.timeout }}" run_event '{"type":"github.scheduled.daily.kstest.${{ matrix.scenario }}","bootIso":{"x86_64":"${{ steps.boot_iso_from_scenario.outputs.boot_iso }}"}}'
+        run: sudo --preserve-env=TEST_JOBS PYTHONPATH=${PYTHONPATH:-}:${{ github.workspace }}/tclib ./pipeline --debug-log permian.log -o library.directPath="${{ github.workspace }}/kickstart-tests/testlib" -o kickstart_test.retry_on_failure=True -o workflows.dry_run=False -o kickstart_test.kstest_local_repo="${{ github.workspace }}/kickstart-tests" -o kickstart_test.timeout="${{ steps.set_timeout.outputs.timeout }}" run_event '{"type":"github.scheduled.daily.kstest.${{ matrix.scenario }}","bootIso":{"x86_64":"${{ steps.boot_iso_from_scenario.outputs.boot_iso }}"},"installationUrls":{"x86_64":{"installation_tree":"${{ steps.set_installation_urls.outputs.installation_tree }}","modular_url":"${{ steps.set_installation_urls.outputs.modular_url }}"}}}'
 
       - name: Collect anaconda logs
         if: always()
